# This workflow will build a package using Maven and then publish it to maven central when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish to Sonatype

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
    - name: Import GPG key
      run: |
        mkdir -p ~/.gnupg
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import

    - name: Publish to GitHub Packages Apache Maven
      run:  ./.lipublish/publish.sh
      shell: bash
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        GPG_PASSWD: ${{ secrets.GPG_PASSWD }}
